package br.com.logistica.api.domain.transporte;

public enum ValidacaoTransportadora {
    ADICIONADO_NO_SISTEMA,
    PREPARANDO_TRANSFERENCIA,
    SOLICITACAO_RASTREIO,
    OBJETO_TRANSFERENCIA,
    CHEGOU_EM_UMA_BASE,
    EM_ROTA,
    ENTREGUE,
    OBJETO_ENTREGUE,
    OBJETO_ENTREGUE_DESTINATARIO,
    OBJETO_ENTREGUE_REMETENTE,
    ENTREGA_REALIZADA,
    EXTRAVIADO,
    CANCELADO,
    DEVOLVIDO
}
